/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    MainHeaderLogin: typeof import('./src/components/MainHeaderLogin.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RecipeCreate: typeof import('./src/components/RecipeCreate.vue')['default']
    RecipeSearch: typeof import('./src/components/RecipeSearch.vue')['default']
    RecipeView: typeof import('./src/components/RecipeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
